# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=1.21.9
yarn_mappings=1.21.9+build.1
loader_version=0.19.2
loom_version=1.16-SNAPSHOT

# Fabric API
fabric_api_version=0.134.1+1.21.9
modmenu_version=16.0.1
clothconfig_version=20.0.149

minecraft_range=>=1.21.9 <=1.21.10